import os

# Email settings
SMTP_USER = os.getenv('APP_SMTP_USER')
SMTP_PASSWORD = os.getenv('APP_SMTP_PASSWORD')
SMTP_HOST = os.getenv('APP_SMTP_HOST')
SMTP_PORT = os.getenv('APP_SMTP_PORT')

ASANA_PROJECT_EMAIL = os.getenv('APP_ASANA_PROJECT_EMAIL')

# Recaptcha Settings
RECAPTCHA_PUBLIC_KEY = os.getenv('APP_RECAPTCHA_PUBLIC_KEY')
RECAPTCHA_PRIVATE_KEY = os.getenv('APP_RECAPTCHA_PRIVATE_KEY')

# CSRF
SECRET_KEY = os.getenv('APP_SECRET_KEY')

# Sentry
SENTRY_DSN = os.getenv('APP_SENTRY_DSN')
